import {Providers} from "./providers";
// These styles apply to every route in the application
import "./globals.css";
import NavBar from "./(componant)/navBar/navBar";
import Footer from "./(componant)/Footer/Footer";
export const metadata = {

  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <NavBar />
        {children}
        <Footer />
      </Providers>
      </body>
    </html>
  );
}
