import { Providers } from "./providers";
// These styles apply to every route in the application
import "./globals.css";
import NavBar from "./(componant)/navBar/navBar";
import Footer from "./(componant)/Footer/Footer";
import ArrowTop from "./(componant)/ArrowTop/ArrowTop";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <NavBar />
          {children}
          <ArrowTop />
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
